[package]
name = "liblmod"
version = "0.2.0"
edition = "2021"
readme = "README.md"
description = "Library for loading Linux kernel modules"
homepage = "https://github.com/zapomnij/liblmod"
repository = "https://github.com/zapomnij/liblmod"
license-file = "LICENSE"

[dependencies]
